// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.12.4
// source: user_service/src/internal/interfaces/output/grpc/session.proto

package grpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SessionValidator_ValidateSession_FullMethodName = "/session.SessionValidator/ValidateSession"
)

// SessionValidatorClient is the client API for SessionValidator service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SessionValidatorClient interface {
	ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionResponse, error)
}

type sessionValidatorClient struct {
	cc grpc.ClientConnInterface
}

func NewSessionValidatorClient(cc grpc.ClientConnInterface) SessionValidatorClient {
	return &sessionValidatorClient{cc}
}

func (c *sessionValidatorClient) ValidateSession(ctx context.Context, in *ValidateSessionRequest, opts ...grpc.CallOption) (*ValidateSessionResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ValidateSessionResponse)
	err := c.cc.Invoke(ctx, SessionValidator_ValidateSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SessionValidatorServer is the server API for SessionValidator service.
// All implementations must embed UnimplementedSessionValidatorServer
// for forward compatibility.
type SessionValidatorServer interface {
	ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionResponse, error)
	mustEmbedUnimplementedSessionValidatorServer()
}

// UnimplementedSessionValidatorServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSessionValidatorServer struct{}

func (UnimplementedSessionValidatorServer) ValidateSession(context.Context, *ValidateSessionRequest) (*ValidateSessionResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ValidateSession not implemented")
}
func (UnimplementedSessionValidatorServer) mustEmbedUnimplementedSessionValidatorServer() {}
func (UnimplementedSessionValidatorServer) testEmbeddedByValue()                          {}

// UnsafeSessionValidatorServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SessionValidatorServer will
// result in compilation errors.
type UnsafeSessionValidatorServer interface {
	mustEmbedUnimplementedSessionValidatorServer()
}

func RegisterSessionValidatorServer(s grpc.ServiceRegistrar, srv SessionValidatorServer) {
	// If the following call pancis, it indicates UnimplementedSessionValidatorServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SessionValidator_ServiceDesc, srv)
}

func _SessionValidator_ValidateSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ValidateSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SessionValidatorServer).ValidateSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SessionValidator_ValidateSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SessionValidatorServer).ValidateSession(ctx, req.(*ValidateSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SessionValidator_ServiceDesc is the grpc.ServiceDesc for SessionValidator service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SessionValidator_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "session.SessionValidator",
	HandlerType: (*SessionValidatorServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "ValidateSession",
			Handler:    _SessionValidator_ValidateSession_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "user_service/src/internal/interfaces/output/grpc/session.proto",
}
