-- Define enums first
-- CREATE TYPE priority_enum AS ENUM ('HIGH', 'MEDIUM', 'LOW');
-- CREATE TYPE status_enum AS ENUM ('TODO', 'IN PROGRESS', 'COMPLETED');

-- Tasks table
CREATE TABLE IF NOT EXISTS TASKS(
    ID SERIAL PRIMARY KEY,
    ASSIGNED_BY INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    ASSIGNED_TO INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TASK_NAME TEXT NOT NULL,
    TASK_DESCRIPTION TEXT ,
    ASSIGNED_AT TIMESTAMPTZ,
    DEADLINE TIMESTAMPTZ,
    PRIORITY priority_enum NOT NULL DEFAULT 'LOW',
    STATUS status_enum NOT NULL DEFAULT 'TODO',
    IS_TRASH BOOLEAN DEFAULT 'FALSE'
);
