-- Users table
CREATE TABLE IF NOT EXISTS USERS(
    ID SERIAL PRIMARY KEY,
    USERNAME VARCHAR(30) NOT NULL UNIQUE,
    PASSWORD TEXT NOT NULL
);

-- Sessions Table
CREATE TABLE  IF NOT EXISTS SESSIONS (
    ID UUID PRIMARY KEY,
    USERID INT NOT NULL REFERENCES USERS(ID) ON DELETE CASCADE,
    TOKENHASH TEXT NOT NULL,
    ISSUED_AT TIMESTAMPTZ NOT NULL,
    EXPIRES_AT TIMESTAMPTZ NOT NULL,
    UNIQUE(USERID)
);